version: 2.1

executors:
  python:
    parameters:
      version:
        type: string
        default: "3.7"

    docker:
      - image: circleci/python:<< parameters.version >>

commands:
  installation:
    parameters:
      test_requirements:
        type: boolean
        default: false

    steps:
      - checkout
      - run:
          name: "Install requirements in a virtual environment."
          command: |
            virtualenv python -q
            source python/bin/activate
            pip config --site set global.progress_bar off
            pip install .

      - when:
          condition: << parameters.test_requirements >>
          steps:
            - run:
                name: "Install test requirements."
                command: |
                  source python/bin/activate
                  pip install -r test-requirements.txt

jobs:
  lint_tests:
    working_directory: ~/composeml
    parameters:
      python_version:
        type: string
        default: "3.7"

    executor:
      name: python
      version: << parameters.python_version >>

    steps:
      - installation:
          test_requirements: true

      - run:
          name: "Run lint tests."
          command: |
            source python/bin/activate
            make lint-tests

  unit_tests:
    working_directory: ~/composeml
    parameters:
      python_version:
        type: string
        default: "3.7"

      codecov:
        type: boolean
        default: false

    executor:
      name: python
      version: << parameters.python_version >>

    steps:
      - installation:
          test_requirements: true

      - when:
          name: "Run unit tests with code coverage."
          condition: << parameters.codecov >>
          steps:
            - run: |
                source python/bin/activate
                make unit-tests ADDOPTS="--cov=composeml"
                codecov

      - unless:
          name: "Run unit tests."
          condition: << parameters.codecov >>
          steps:
            - run: |
                source python/bin/activate
                make unit-tests

workflows:
  version: 2
  "Integration Tests":
    jobs:
      - lint_tests:
          name: "Lint Tests - Python 3.6"
          python_version: "3.6"

      - lint_tests:
          name: "Lint Tests - Python 3.7"
          python_version: "3.7"

      - lint_tests:
          name: "Lint Tests - Python 3.8"
          python_version: "3.8"

      - unit_tests:
          name: "Unit Tests - Python 3.6"
          python_version: "3.6"

      - unit_tests:
          name: "Unit Tests - Python 3.7"
          python_version: "3.7"

      - unit_tests:
          name: "Unit Tests - Python 3.8"
          python_version: "3.8"
