version: 2.1

jobs:
  test_python:
    parameters:
      python_version:
        type: string
        default: "3.7"
      codecov:
        type: boolean
        default: false
    working_directory: ~/compose
    docker:
        - image: circleci/python:<< parameters.python_version >>
    steps:
      - checkout
      - run: |
          virtualenv << parameters.python_version >> -q
          source << parameters.python_version >>/bin/activate
          make installdeps
      - run: |
          source << parameters.python_version >>/bin/activate
          make lint
      - run: |
          source << parameters.python_version >>/bin/activate
          coverage erase
          make test
      - when:
          condition: << parameters.codecov >>
          steps:
            - run: |
              codecov

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - test_python:
          python_version: "3.5"
      - test_python:
          python_version: "3.6"
      - test_python:
          python_version: "3.7"
          codecov: true
