version: 2
jobs:
  "python-35":
    working_directory: ~/compose-ml
    docker:
        - image: circleci/python:3.5
    steps:
      - checkout
      - run: virtualenv venv_35
      - restore_cache:
          key: python35-{{ checksum "requirements.txt" }}
      - run: source venv_35/bin/activate && make installdeps
      - save_cache:
          key: python35-{{ checksum "requirements.txt" }}
          paths:
            - "venv_35"
      - run: source venv_35/bin/activate && make lint
      - run: |
          source venv_35/bin/activate
          coverage erase
          make optimized_test
  "python-27":
    working_directory: ~/premium-primitives
    docker:
        - image: circleci/python:2.7
    steps:
      - checkout
      - run: virtualenv venv_27
      - run: source venv_27/bin/activate && python generate_requirements.py
      - restore_cache:
          key: python27-{{ checksum "requirements.txt" }}
      - run: source venv_27/bin/activate && make installdeps
      - save_cache:
          key: python27-{{ checksum "requirements.txt" }}
          paths:
            - "venv_27"
      - run: |
          source venv_27/bin/activate
          make clean
          make optimized_test_py27

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "python-35"
      - "python-27"